### ISSUE TITLE
is_an? issue

### ISSUE THREAD

**Issue by beornborn** [smileart/british#1]
https://github.com/smileart/british/blob/master/lib/british.rb#L97-L101

``` ruby
  # Public: British alias of native is_a? method
  # Returns the original method's result
  def is_an?(*args)
    is_a?(*args) if respond_to?(:is_a?)
  end
```

fortunately, all the objects have is_a? method. 
but with checking if respond_to?(:is_a?) you suppose that there exist objects that don't respond to is_a?
e. g. inherited from BasicObject.
and your 'is_an?' will not raise in that case expected NoMethodError but just return nil

**Comment by smileart** [comment]
Sure, you are right. Will fix it in the next version. :+1: Thanks!
